### ISSUE TITLE
wifi Integration

### ISSUE THREAD

**Issue by blue2111** [plmilord/Hass.io-custom-component-ikamand#15]
I tried to connect the the Ikanand with my Wifi but i used base64 and encoded my SSID and i entered the password of my wifi, i also tried to encode my password but the ikamand isn't able to connect. Is a "Space" in the SSID perhaps a problem?

**Comment by plmilord** [comment]
You need to base64 encode the SSID and password. For "Space", I really don't know.

Are you trying to join a 2.4GHz only network or a Smart Connect network (i.e. it will switch from 2.4 to 5 depending on...)?

Let us know your findings.
