### ISSUE TITLE
Deprecated Features used

### ISSUE THREAD

**Issue by HiChenJo** [plmilord/Hass.io-custom-component-ikamand#6]
Hey HomeAssistant Logger throws some errors:

Entity None (<class 'custom_components.ikamand.climate.IkamandThermostat'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE: 1>, please create a bug report at https://github.com/plmilord/Hass.io-custom-component-ikamand/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

SUPPORT_TARGET_TEMPERATURE was used from ikamand, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/plmilord/Hass.io-custom-component-ikamand/issues
HVAC_MODE_HEAT was used from ikamand, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/plmilord/Hass.io-custom-component-ikamand/issues
HVAC_MODE_OFF was used from ikamand, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/plmilord/Hass.io-custom-component-ikamand/issues

**Comment by plmilord** [comment]
Thanks @HiChenJo for the hint. I'll be back soon with a new version.

**Comment by plmilord** [comment]
Everything should be fine with iKamand v1.4

Thanks,
