### ISSUE TITLE
"Unable to connect to this iKamand device, please try again"

### ISSUE THREAD

**Issue by botkiller** [plmilord/Hass.io-custom-component-ikamand#7]
Hello! I'm attempting to unbrick my wife's iKamand using your instructions and feel like I'm so close, but can't resolve this last issue. 

I was able to add the custom_components and confirmed iKamand shows up as a custom integration in Home Assistant. I was also able to get the iKamand connected to my wifi network (thanks to your awesome instructions w/ the QR code!) and it rebooted and the wifi light turned solid blue for a while... I thought it was good to go, but trying to add the integration in Home Assistant fails on the first step. When I input the host name I get the error, "Unable to connect to this iKamand device, please try again". 

I've confirmed that this is the correct IP address via my router, but also noted that the iKamand intermittently "resets" its wifi connection and becomes unreachable approximately every 30 seconds. I'm assuming this is not expected? 
<img width="991" alt="ikamand" src="https://github.com/plmilord/Hass.io-custom-component-ikamand/assets/13300981/0f0022f6-a3fe-4c41-8540-db0b0c1f7168">

The one extra wrinkle is that this iKamand was never set up prior to being bricked by Kamado. It was still in box and very likely has older firmware. Do you know if the firmware version could impact the first time setup or its usage in Home Assistant? Maybe there's some server it expects to exist for pinging to test its Internet connection, but the server has been taken down?

Thanks in advance, and again for your hard work on this project!

**Comment by plmilord** [comment]
Interesting... make sure to base64 encode your SSID **and** your PASSWORD.

I'm not sure if it's even an unused device... In my opinion it should work the same!

Let me know if you find something.

Pierre-Luc

**Comment by botkiller** [comment]
Thanks! I'm definitely encoding both the SSID and Password. I've also tested inputting a known-bad password and it produces a different result where the blue wifi light blinks instead of remaining steady. I also don't see it get an IP from my router in those instances, where it does with the setup I mentioned in the original comment. Seems we've got an (even more) unlucky one!

Thanks again for your help.

**Comment by plmilord** [comment]
You try to connect a 2.4Ghz Wifi network?

**Comment by botkiller** [comment]
Yep, definitely on a 2.4GHz network. For some proof of that (just to make sure I'm sane) here is the mac address of our iKamand from the netset admin page: 
![IMG_8171](https://github.com/plmilord/Hass.io-custom-component-ikamand/assets/13300981/7a1a834d-21a0-46bb-bc35-e70725205616)

And here is the same device in my router admin page where it's clearly connected to the 2.4GHz network and assigned IP 192.168.0.227: 
![IMG_8182](https://github.com/plmilord/Hass.io-custom-component-ikamand/assets/13300981/19795f3c-051c-4172-b57b-a3583372fdf4)

So it seems to connect just fine, but after ~30 seconds it drops the connection and reconnects. And for whatever reason, during the brief time it is connected, entering 192.168.0.227 as the Host Name while adding the integration in Home Assistant produces the "Unable to connect to this iKamand device" message.

**Comment by plmilord** [comment]
I don't know if it needs the app for first use... As said, it looks a bit crazy! Are you using the Smart Connect feature (will automatically assign 2.4Ghz or 5Ghz depending on negotiation with things) within your Wifi router?

If you have the option to try it on another WiFi, this will help you determine if your home WiFi is the cause.

let me know your progress.


PL
